---
services:
  _defaults:
    autowire: true
    autoconfigure: true

  Infra\Symfony\Event\Listener\:
    resource: '%kernel.project_dir%/src/Infra/Symfony/Event/Listener'
    tags: [ kernel.event_listener ]

  Infra\Symfony\Event\Listener\AllowPreflightRequestListener:
    tags:
      - { name: kernel.event_listener, event: kernel.request, priority: 512 }

  Infra\Symfony\Event\Listener\HandleCORSPermissionListener:
    tags:
      - { name: kernel.event_listener, event: kernel.response }
