---
doctrine:
  dbal:
    driver: pdo_mysql
    host: '%mysql_host%'
    port: '%mysql_port%'
    dbname: '%mysql_database%'
    user: '%mysql_user%'
    password: '%mysql_password%'
    server_version: '%mysql_version%'
    charset: utf8mb4

    types:
      uuid: Infra\Doctrine\DBAL\Types\UUIDType

  orm:
    auto_generate_proxy_classes: true
    enable_lazy_ghost_objects: true
    report_fields_where_declared: true
    validate_xml_mapping: true
    naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
    auto_mapping: true
    mappings:
      Identity:
        is_bundle: false
        type: yml
        dir: '%kernel.project_dir%/config/doctrine/mapping/Identity'
        prefix: Domain\Identity
        alias: Identity
      Model:
        is_bundle: false
        type: yml
        dir: '%kernel.project_dir%/config/doctrine/mapping/Model'
        prefix: Domain\Model
        alias: Model

when@test:
  doctrine:
    dbal:
      dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
  doctrine:
    orm:
      auto_generate_proxy_classes: false
      proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
      query_cache_driver:
        type: pool
        pool: doctrine.system_cache_pool
      result_cache_driver:
        type: pool
        pool: doctrine.result_cache_pool

  framework:
    cache:
      pools:
        doctrine.result_cache_pool:
          adapter: cache.app
        doctrine.system_cache_pool:
          adapter: cache.system
